In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\User\Desktop\iween\matches.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   Season           756 non-null    object
 2   city             749 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    object
 14  venue            756 non-null    object
 15  umpire1          754 non-null    object
 16  umpire2          754 non-null    object
 17  umpire3          119 non-null    object
dtypes: int64(4), object(14)
memory usage: 106.4+ KB

In [4]:
#Data Cleaning
df['city'] =df['city'].fillna('Unknown')
df['winner'] =df['winner'].fillna('Unknown')
df['player_of_match'] = df['player_of_match'].fillna('Unknown')
df['umpire1'] = df['umpire1'].fillna('Unknown')
df['umpire2'] = df['umpire2'].fillna('Unknown')
df.drop('umpire3',axis=1,inplace=True)

In [5]:
df.duplicated().sum()
df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   Season           756 non-null    object
 2   city             756 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           756 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  756 non-null    object
 14  venue            756 non-null    object
 15  umpire1          756 non-null    object
 16  umpire2          756 non-null    object
dtypes: int64(4), object(13)
memory usage: 100.5+ KB

In [6]:
#Total number of matches

total_matches = df.shape[0]
print(f"Total Matches: {total_matches}")

Total Matches: 756

In [7]:
#Column names

columns = df.columns.to_list()
print("Columns:")
for column in columns:
    print(column)

Columns:
id
Season
city
date
team1
team2
toss_winner
toss_decision
result
dl_applied
winner
win_by_runs
win_by_wickets
player_of_match
venue
umpire1
umpire2

In [8]:
# First 5 rows of data

top_five = df.head(5)
print("Top 5:")
print(top_five)

Top 5:
   id    Season       city        date                        team1  \
0   1  IPL-2017  Hyderabad  05-04-2017          Sunrisers Hyderabad
1   2  IPL-2017       Pune  06-04-2017               Mumbai Indians
2   3  IPL-2017     Rajkot  07-04-2017                Gujarat Lions
3   4  IPL-2017     Indore  08-04-2017       Rising Pune Supergiant
4   5  IPL-2017  Bangalore  08-04-2017  Royal Challengers Bangalore

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field
1       Rising Pune Supergiant       Rising Pune Supergiant         field
2        Kolkata Knight Riders        Kolkata Knight Riders         field
3              Kings XI Punjab              Kings XI Punjab         field
4             Delhi Daredevils  Royal Challengers Bangalore           bat

   result  dl_applied                       winner  win_by_runs  \
0  normal           0          Sunrisers Hyderabad           35
1  normal           0       Rising Pune Supergiant            0
2  normal           0        Kolkata Knight Riders            0
3  normal           0              Kings XI Punjab            0
4  normal           0  Royal Challengers Bangalore           15

   win_by_wickets player_of_match                                      venue  \
0               0    Yuvraj Singh  Rajiv Gandhi International Stadium, Uppal
1               7       SPD Smith    Maharashtra Cricket Association Stadium
2              10         CA Lynn     Saurashtra Cricket Association Stadium
3               6      GJ Maxwell                     Holkar Cricket Stadium
4               0       KM Jadhav                      M Chinnaswamy Stadium

          umpire1        umpire2
0     AY Dandekar       NJ Llong
1  A Nand Kishore         S Ravi
2     Nitin Menon      CK Nandan
3    AK Chaudhary  C Shamshuddin
4         Unknown        Unknown

In [9]:
#Describe the data

df.describe()

                 id  dl_applied  win_by_runs  win_by_wickets
count    756.000000  756.000000   756.000000      756.000000
mean    1792.178571    0.025132    13.283069        3.350529
std     3464.478148    0.156630    23.471144        3.387963
min        1.000000    0.000000     0.000000        0.000000
25%      189.750000    0.000000     0.000000        0.000000
50%      378.500000    0.000000     0.000000        4.000000
75%      567.250000    0.000000    19.000000        6.000000
max    11415.000000    1.000000   146.000000       10.000000

In [10]:
# Which player has won the most “Player of the Match” awards in games decided on the final ball?

matches=df[(df['win_by_runs']==1) | (df['win_by_wickets']==1)]
player_of_the_match = matches['player_of_match'].value_counts().idxmax()
print(f"Player of the Match: {player_of_the_match}")

Player of the Match: KH Pandya

In [11]:
# At Wankhede Stadium, is it more common to win by batting first (runs) or by batting second

stadium= df[df['venue']=='Wankhede Stadium']

stadium['winner'].value_counts()

winner
Mumbai Indians                 42
Chennai Super Kings             7
Kings XI Punjab                 5
Rajasthan Royals                4
Royal Challengers Bangalore     3
Rising Pune Supergiant          2
Delhi Daredevils                2
Kochi Tuskers Kerala            1
Deccan Chargers                 1
Pune Warriors                   1
Kolkata Knight Riders           1
Rising Pune Supergiants         1
Gujarat Lions                   1
Sunrisers Hyderabad             1
Delhi Capitals                  1
Name: count, dtype: int64

In [12]:
# Which team has the highest number of wins where the victory margin was greater than 50 runs?
win_greater_50 = df[df['win_by_runs']>50]
team = win_greater_50['winner'].value_counts().idxmax()

print(f"Team has the highest number of wins where the victory margin was greater than 50 runs: {team}")

Team has the highest number of wins where the victory margin was greater than 50 runs: Chennai Super Kings

In [13]:
# How many times has the team that won the toss also set a target and won the match?

df[df['toss_winner']==df['winner']]
# df.groupby(df['win_by_runs'],df['winner'])

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,Unknown,Unknown
5,6,IPL-2017,Hyderabad,09-04-2017,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,11346,IPL-2019,Mohali,05-05-2019,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,KL Rahul,IS Bindra Stadium,KN Ananthapadmanabhan,C Shamshuddin
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,Unknown,Unknown
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould

In [14]:
# Which of the two umpires (umpire1 or umpire2) has officiated more matches involving the Kolkata Knight Riders?
match_kkr = df[(df['team1'] == 'Kolkata Knight Riders') | (df['team2'] == 'Kolkata Knight Riders')]
umpire1 = match_kkr['umpire1'].value_counts().idxmax()
umpire2 = match_kkr['umpire2'].value_counts().idxmax()
print(f"Umpires officiated more matches involving the Kolkata Knight Riders are:")
print(umpire1)
print(umpire2)

Umpires officiated more matches involving the Kolkata Knight Riders are:
Asad Rauf
S Ravi